### PR TITLE
Assignment#2 Lists done

### PR DESCRIPTION
**Pull request by s-bose**
Lists exercise done from assignment 2

### CODE REVIEW

**Comment by sushilm2011** [comment]
Numpy Exercise Q1. It's 64 subdivisions. Also complete numpy examples

**Comment by s-bose** [comment]
Oh sorry. My bad. 
Also, how do I complete the examples? They already have the solutions given.

**Comment by sushilm2011** [comment]
Just run the cells and save that executed notebook.

**Comment by s-bose** [comment]
Okay. Got it.

**Pull request merged**
