### PR TITLE
Done

### PR DESCRIPTION
**Pull request by divyarachel**
Hi there!i have solved my assignment.Please check it out

### CODE REVIEW

**Comment by sushilm2011** [comment]
Numpy exercise: For the intersection expected output is [2, 4]  yours is [2,2,4,4]
Also in numpy exercises last question you can also use extended slice for example:
a = np.arange(10)
a[::3]

**Comment by divyarachel** [comment]
Thanks 😅

**Comment by divyarachel** [comment]
So my  pull request is not acceptable?😶

**Comment by sushilm2011** [comment]
Change that and again send a pull request it will be merged

**Pull request closed without merging**
