### PR TITLE
Revert "Soumak majumdar"

### PR DESCRIPTION
**Pull request by captain-pool**
Reverts MLCCKolkata/Assignment-2#115

### CODE REVIEW

**Comment by captain-pool** [comment]
@SoumakMajumdar Can You please put the notebook in your branch and create a pull request again??

**Comment by soumakofc** [comment]
Hey, please check once again... The notebook is on my branch...
Actually when I have done the assignment 2 at first, I created a pull
request on the master branch by mistake... But again I also created a pull
request in my branch also...
Please recheck once...

Thank you.

**Comment by captain-pool** [comment]
Yes, I've seen that PR. It was a mistake from my part. After you created the PR, I mistakenly accepted the one which commits to main branch. So, I had to remove your PRs.
Create a fresh PR and I'll merge it.
Any inconvenience caused is deeply apologized.

**Comment by soumakofc** [comment]
Okay... Not a problem at all... I will make a new PR by today...

**Comment by soumakofc** [comment]
Hey, I am unable to make a new PR...

**Comment by captain-pool** [comment]
It's done. Don't worry.

**Comment by SoumakMajumdar** [comment]
Hey,

I just signed the petition "People assaulting doctors should be punished
like Terrorists" and wanted to see if you could help by adding your name.

Our goal is to reach 150,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/F7bZ9DDxJR

Thanks!
Soumak

**Pull request merged**
