### PR TITLE
Problem solved(List)

### PR DESCRIPTION
**Pull request by vaibhavkumar049**
list is solved

### CODE REVIEW

**Comment by sushilm2011** [comment]
Complete all the exercises and then send a pull request

**Comment by vaibhavkumar049** [comment]
completed both assignment please merge

**Comment by vaibhavkumar049** [comment]
@sushilm2011 please check this assignment and merge it

**Comment by sushilm2011** [comment]
I don't see numpy examples in your branch.

**Comment by vaibhavkumar049** [comment]
I thought that is example and we don't have to solve it. but anyways solved that one too

**Pull request merged**
