### PR TITLE
Completed the list colab exercise from Assignment-2.

### PR DESCRIPTION
**Pull request by jddeep**
Done with the lists exercise from Assignment-2 MLCC DSC Kolkata edition.
Name-Jaideep Prasad

### CODE REVIEW

**Comment by sushilm2011** [comment]
Complete all the exercises.

**Comment by sushilm2011** [comment]
Numpy Exercise is not complete. Complete and then send a pull request.

**Comment by sushilm2011** [comment]
Needs Some Corrections in Numpy Exercises: 
1. Q2: Its 3*n not 2*n
2. Q7. By frame it means padding 1s all around the 2d array e.g
  1 1 1 1
  1 0 0 1
  1 0 0 1
  1 1 1 1
3. Q8. See [checkerboard](https://en.wikipedia.org/wiki/Checkerboard) for understanding the meaning.

**Comment by jddeep** [comment]
Please my one and only PR other than this it has the actual completed Assignment 2

**Pull request closed without merging**
